import numpy as np
# 1. Calculate the total revenue generated by two product categories in a store
print("__________Answer 1__________")
# Input:
category1_revenue = np.array([500, 600, 700, 550])
category2_revenue = np.array([450, 700, 800, 600])

total_revenue = np.add(category1_revenue,category2_revenue)
print("Total revenue:",total_revenue)


# 2. Calculate the profit made by a company
print("\n__________Answer 2__________")
# Input:
revenue = np.array([10000, 12000, 11000, 10500])
expenses = np.array([4000, 5000, 4500, 4800])

profit = np.subtract(revenue,expenses)
print("Profit made by company is:",profit)


# 3. Determine which products in a store are out of stock (quantity is 0).
# Input:
inventory = np.array([10, 0, 5, 0, 20, 0])
# Output:
# Out of Stock Products: [0 0 0]
print("\n__________Answer 3__________")
Out_of_stock = np.where(inventory == 0)
print("Out of Stock Product:")

for i in Out_of_stock:
    print(inventory[i])


# 4.Calculate the total cost of items in a shopping cart, considering the quantity and price per item.
print("\n__________Answer 4__________")
# Input:
quantity = np.array([2, 3, 4, 1])
price_per_item = np.array([10.0, 5.0, 8.0, 12.0])

total_cost = np.multiply(quantity,price_per_item)
print("Total Cost of Items:", total_cost)








