import numpy as np
import matplotlib.pyplot as plt
# Lab1: Analyze the relationship between the size of houses (measured in square footage) and their selling prices in a particular neighborhood.
# You have collected data on various houses in that neighborhood.Create a scatter plot using the below data and share your conclusion/analysis.
# Input:
square_footage = np.array([1200, 1400, 1600, 1800, 2000, 2200, 2400, 2600, 2800, 3000])
selling_prices = np.array([250, 290, 315, 380, 410, 450, 500, 525, 570, 610])
plt.plot(square_footage,selling_prices, "o")
print(plt.show())


# Lab2: Create a pie chart to visualize the distribution of your monthly income by source. You have collected data on the various sources of your income,
# such as salary, freelance work, investments, and rental income. Share your conclusion/analysis.
# Input:
income_sources = ['Salary', 'Freelance', 'Investments', 'Rental', 'Other']
monthly_income = [5000, 1500, 1000, 600, 400]
plt.pie(monthly_income,labels=income_sources)
print(plt.show())


# Lab3: Create a pie chart to illustrate the distribution of a company's revenue across its various business segments. You have collected data on the revenue
# generated by each segment, such as Product A, Product B, Services, and Licensing. Share your conclusion/analysis.
# Input:
segments = ['Product A', 'Product B', 'Services', 'Licensing']
revenue_percentages = [45, 25, 15, 15]
plt.pie(revenue_percentages, labels=segments)
print(plt.show())


# Lab4: Suppose you're a sales manager for an e-commerce company, and you want to create a figure with subplots to compare the sales performance of
# different product categories over time. You have sales data for four product categories: Electronics, Clothing, Home & Garden, and Sports & Outdoors. Share
# your conclusion/analysis.
# Input:
months = np.arange(1, 13)
electronics_sales = np.array([25000, 28000, 31000, 27000, 30000, 32000, 35000,
36000, 38000, 39000, 41000, 42000])
clothing_sales = np.array([15000, 16000, 17000, 18000, 19000, 20000, 21000, 22000,
23000, 24000, 25000, 26000])
home_garden_sales = np.array([18000, 19000, 20000, 21000, 22000, 23000, 24000,
25000, 26000, 27000, 28000, 29000])
sports_outdoors_sales = np.array([12000, 13000, 14000, 15000, 16000, 17000, 18000,
19000, 20000, 21000, 22000, 23000])

plt.subplot(2, 2, 1)
plt.plot(months, electronics_sales, 'b-o')
plt.title('Electronics')

plt.subplot(2,2,2)
plt.plot(months, clothing_sales, 'b-o')
plt.title('Clothing')

plt.subplot(2,2,3)
plt.plot(months, home_garden_sales, 'b-o')
plt.title('Home Garden')

plt.subplot(2,2,4)
plt.plot(months, sports_outdoors_sales, 'b-o')
plt.title('Sports')

plt.show()
